eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.122:8761/eureka/

zuul:
  prefix: /tkn-api
  routes:
    reply-server:
      path: /reply-server/**
      serviceId: REPLY-SERVER-CCO
    reply-alarm:
      path: /reply-alarm/**
      serviceId: REPLYALARMSERVER
server:
  port: 8090

spring:
  application:
    name: zuul-proxy